### ISSUE TITLE
Error while connecting through API

### ISSUE THREAD

**Issue by flotho** [OCA/e-commerce#152] opened 2017-01-09 17:21 UTC
Hi,

I have the following error through API :
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/openerp/service/wsgi_server.py", line 56, in xmlrpc_return
    result = openerp.http.dispatch_rpc(service, method, params)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 114, in dispatch_rpc
    result = dispatch(method, params)
  File "/usr/lib/python2.7/site-packages/openerp/service/common.py", line 57, in dispatch
    return g[exp_method_name](*params)
  File "/usr/lib/python2.7/site-packages/openerp/service/common.py", line 23, in exp_login
    res = security.login(db, login, password)
  File "/usr/lib/python2.7/site-packages/openerp/service/security.py", line 9, in login
    return res_users._login(db, login, password)
  File "/usr/lib/python2.7/site-packages/openerp/addons/base/res/res_users.py", line 462, in _login
    self.check_credentials(cr, user_id, password)
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 354, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/additional_repos/OCA-ecommerce/website_sale_wishlist/models/res_users.py", line 27, in check_credentials
    self.env["product.wishlist"]._join_current_user_and_session()
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/additional_repos/OCA-ecommerce/website_sale_wishlist/models/product_wishlist.py", line 72, in _join_current_user_and_session
    ("session", "=", request.session.sid),
  File "/usr/lib/python2.7/site-packages/werkzeug/local.py", line 343, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/usr/lib/python2.7/site-packages/werkzeug/local.py", line 302, in _get_current_object
    return self.__local()
  File "/usr/lib/python2.7/site-packages/werkzeug/local.py", line 135, in _lookup
    raise RuntimeError('object unbound')
RuntimeError: object unbound
```
Impossible to connect via the API

**Comment by lasley** [comment] 2017-01-16 23:19
Hi @flotho - What are you attempting to do in the API that triggers this error? Are you able to reproduce on Runbot?

**Comment by py-prak** [comment] 2017-04-03 11:16
@lasley @flotho Is there any update on this issue ? I am facing the same one.

**Comment by lasley** [comment] 2017-04-03 15:14
@py-prak - no, because we do not have proper information to diagnose. 

If you could please provide some replication steps, that would be great. Otherwise, I propose that a PSC close this issue due to lack of information and response.

**Comment by flotho** [comment] 2017-06-26 19:29
Hi @lasley 
I reproduced the same error on runbot :
```
Traceback (most recent call last):
  File "/.repo_requirements/odoo/openerp/service/wsgi_server.py", line 56, in xmlrpc_return
    result = openerp.http.dispatch_rpc(service, method, params)
  File "/.repo_requirements/odoo/openerp/http.py", line 115, in dispatch_rpc
    result = dispatch(method, params)
  File "/.repo_requirements/odoo/openerp/service/common.py", line 57, in dispatch
    return g[exp_method_name](*params)
  File "/.repo_requirements/odoo/openerp/service/common.py", line 23, in exp_login
    res = security.login(db, login, password)
  File "/.repo_requirements/odoo/openerp/service/security.py", line 9, in login
    return res_users._login(db, login, password)
  File "/.repo_requirements/odoo/openerp/addons/base/res/res_users.py", line 462, in _login
    self.check_credentials(cr, user_id, password)
  File "/.repo_requirements/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/.repo_requirements/odoo/openerp/api.py", line 354, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/odoo/build/OCA/e-commerce/website_sale_wishlist/models/res_users.py", line 27, in check_credentials
    self.env["product.wishlist"]._join_current_user_and_session()
  File "/.repo_requirements/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/odoo/build/OCA/e-commerce/website_sale_wishlist/models/product_wishlist.py", line 72, in _join_current_user_and_session
    ("session", "=", request.session.sid),
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 338, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 297, in _get_current_object
    return self.__local()
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 132, in _lookup
    raise RuntimeError('object unbound')
RuntimeError: object unbound

```

Database used : 
9.0 : http://3294646-9-0-05c08c.runbot1.odoo-community.org/
10.0 : http://3296172-10-0-6f996a.runbot2.odoo-community.org

Same issue

**Comment by lasley** [comment] 2017-06-26 20:02
@flotho - Thanks for the test case. It seems interesting to me that the request session is not set during an API interaction. cc @Yajo

**Comment by flotho** [comment] 2017-06-26 20:04
@lasley , you're welcome,

**Comment by yajo** [comment] 2017-06-27 08:01
What steps did you follow to get to the error?

**Comment by flotho** [comment] 2017-06-27 14:35
I used an external lib in Java that we are supporting https://github.com/DeBortoliWines/openerp-java-api and try to connect to a db with wishlist module

**Comment by RoelAdriaans** [comment] 2017-07-13 13:15
Same issue with the default python xml-rpc api:

```python
import xmlrpclib

# Database and openerp settings:
username = "admin"
pwd = "admin"
dbname = "test"
oeserver = "http://odoo-server"

print "connecting to odoo"
sock_common = xmlrpclib.ServerProxy(oeserver +"/xmlrpc/common")
print "Do a login"
uid = sock_common.login(dbname, username, pwd)
print "uid found", uid
sock = xmlrpclib.ServerProxy(oeserver + "/xmlrpc/object")
```

And the traceback from this script:
```python
connecting to odoo
Do a login
Traceback (most recent call last):
  File "connect.py", line 13, in <module>
    uid = sock_common.login(dbname, username, pwd)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1316, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1493, in parse_response
    return u.close()
  File "/usr/lib/python2.7/xmlrpclib.py", line 800, in close
    raise Fault(**self._stack[0])
xmlrpclib.Fault: <Fault object unbound: 'Traceback (most recent call last):
  File "/opt/odoo/test/odoo/odoo/service/wsgi_server.py", line 56, in xmlrpc_return
    result = odoo.http.dispatch_rpc(service, method, params)
  File "/opt/odoo/test/odoo/odoo/http.py", line 118, in dispatch_rpc
    result = dispatch(method, params)
  File "/opt/odoo/test/odoo/odoo/service/common.py", line 57, in dispatch
    return g[exp_method_name](*params)
  File "/opt/odoo/test/odoo/odoo/service/common.py", line 23, in exp_login
    res = security.login(db, login, password)
  File "/opt/odoo/test/odoo/odoo/service/security.py", line 9, in login
    return res_users._login(db, login, password)
  File "/opt/odoo/test/odoo/odoo/addons/base/res/res_users.py", line 455, in _login
    user.sudo(user_id).check_credentials(password)
  File "/opt/odoo/test/website_sale_wishlist/models/res_users.py", line 27, in check_credentials
    self.env["product.wishlist"]._join_current_user_and_session()
  File "/opt/odoo/test/website_sale_wishlist/models/product_wishlist.py", line 71, in _join_current_user_and_session
    ("session", "=", request.session.sid),
  File "/usr/lib/python2.7/dist-packages/werkzeug/local.py", line 338, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/usr/lib/python2.7/dist-packages/werkzeug/local.py", line 297, in _get_current_object
    return self.__local()
  File "/usr/lib/python2.7/dist-packages/werkzeug/local.py", line 132, in _lookup
    raise RuntimeError(\'object unbound\')
RuntimeError: object unbound
'>

```

**Comment by yajo** [comment] 2017-07-17 07:33
Yeah, the problem's clear: we should check the existence of the session before attempting to use it.

**Comment by pedrobaeza** [comment] 2021-02-09 17:06
Triaging.

**Closed as completed by pedrobaeza** 2021-02-09 17:06 UTC
Labels: bug, needs fixing
