### ISSUE TITLE
[16.0] website_sale_checkout_skip_payment can't installing

### ISSUE THREAD

**Issue by allan3566** [OCA/e-commerce#948] opened 2024-07-04 08:10 UTC
## Module
website_sale_checkout_skip_payment

## Describe the bug
The module "website_sale_checkout_skip_payment" can't be install. The following error is displayed:
##
Traceback (most recent call last):
  File "C:\odoo_17\odoo_16\odoo\odoo\http.py", line 1764, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\odoo_17\odoo_16\odoo\odoo\service\model.py", line 133, in retrying
    result = func()
             ^^^^^^
  File "C:\odoo_17\odoo_16\odoo\odoo\http.py", line 1791, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\odoo_17\odoo_16\odoo\odoo\http.py", line 1995, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\odoo_17\odoo_16\odoo\addons\website\models\ir_http.py", line 235, in _dispatch
    response = super()._dispatch(endpoint)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\odoo_17\odoo_16\odoo\odoo\addons\base\models\ir_http.py", line 222, in _dispatch
    result = endpoint(**request.params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\odoo_17\odoo_16\odoo\odoo\http.py", line 741, in route_wrapper
    result = endpoint(self, *args, **params_ok)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\odoo_17\odoo_16\odoo\addons\web\controllers\dataset.py", line 28, in call_button
    action = self._call_kw(model, method, args, kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\odoo_17\odoo_16\odoo\addons\web\controllers\dataset.py", line 20, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\odoo_17\odoo_16\odoo\odoo\api.py", line 468, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\odoo_17\odoo_16\odoo\odoo\api.py", line 453, in _call_kw_multi
    result = method(recs, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<decorator-gen-77>", line 2, in button_immediate_install
  File "C:\odoo_17\odoo_16\odoo\odoo\addons\base\models\ir_module.py", line 75, in check_and_log
    return method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\odoo_17\odoo_16\odoo\odoo\addons\base\models\ir_module.py", line 466, in button_immediate_install
    return self._button_immediate_function(self.env.registry[self._name].button_install)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\odoo_17\odoo_16\odoo\odoo\addons\base\models\ir_module.py", line 590, in _button_immediate_function
    registry = modules.registry.Registry.new(self._cr.dbname, update_module=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<decorator-gen-16>", line 2, in new
  File "C:\odoo_17\odoo_16\odoo\odoo\tools\func.py", line 87, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\odoo_17\odoo_16\odoo\odoo\modules\registry.py", line 113, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "C:\odoo_17\odoo_16\odoo\odoo\modules\loading.py", line 480, in load_modules
    processed_modules += load_marked_modules(env, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\odoo_17\odoo_16\odoo\odoo\modules\loading.py", line 364, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "C:\odoo_17\odoo_16\odoo\odoo\modules\loading.py", line 227, in load_module_graph
    load_data(env, idref, mode, kind='data', package=package)
  File "C:\odoo_17\odoo_16\odoo\odoo\modules\loading.py", line 71, in load_data
    tools.convert_file(env, package.name, filename, idref, mode, noupdate, kind)
  File "C:\odoo_17\odoo_16\odoo\odoo\tools\convert.py", line 627, in convert_file
    convert_xml_import(env, module, fp, idref, mode, noupdate)
  File "C:\odoo_17\odoo_16\odoo\odoo\tools\convert.py", line 693, in convert_xml_import
    obj.parse(doc.getroot())
  File "C:\odoo_17\odoo_16\odoo\odoo\tools\convert.py", line 613, in parse
    self._tag_root(de)
  File "C:\odoo_17\odoo_16\odoo\odoo\tools\convert.py", line 567, in _tag_root
    raise ParseError(msg) from None  # Restart with "--log-handler odoo.tools.convert:DEBUG" for complete traceback
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
odoo.tools.convert.ParseError: while parsing None:5
Error while parsing or validating view:

Element ![image](https://github.com/OCA/e-commerce/assets/44181994/7969e629-109f-4bb7-8dc2-b702878c08bf) cannot be located in parent view

View error context:
{'file': 'c:\\odoo_17\\odoo_16\\odoo\\addons_custom\\website_sale_checkout_skip_payment\\views\\website_sale_template.xml',
 'line': 2,
 'name': 'payment',
 'view': ir.ui.view(1965,),
 'view.model': False,
 'view.parent': ir.ui.view(1788,),
 'xmlid': 'payment'}

## To Reproduce
Click on the "ACTIVATE" button on the "Website Sale Checkout Skip Paymnet" module within the "Apps" section of Odoo.

**Expected behavior**
The module should install without errors

**Affected versions:**
16.0.1.1.0

**Comment by pedrobaeza** [comment] 2024-07-06 12:32
The module is working in a fresh DB. Yours should have incompatible content, but it's not a fault of the module. You can ask for help on Odoo forums, but closing, as this is not a bug in the module code.

**Closed as completed by pedrobaeza** 2024-07-06 12:32 UTC
Labels: bug
